/**
 * ubrn regenerates src/index.ts and may stub cpp/react-native-payjoin.cpp.
 * Restore SatSigner facade re-exports and registerModule wiring.
 */
const fs = require('fs')
const path = require('path')

const cppPath = path.join(__dirname, '..', 'cpp', 'react-native-payjoin.cpp')
const cppContents = `// Generated by uniffi-bindgen-react-native — registerModule call required.
#include "react-native-payjoin.h"
#include "generated/satsigner_payjoin.hpp"

namespace payjoin {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeSatsignerPayjoin::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		NativeSatsignerPayjoin::unregisterModule(runtime);
		return false;
	}
}
`
fs.writeFileSync(cppPath, cppContents)
console.log('patched cpp/react-native-payjoin.cpp with registerModule')

const cmakePath = path.join(__dirname, '..', 'android', 'CMakeLists.txt')
if (fs.existsSync(cmakePath)) {
  let cmake = fs.readFileSync(cmakePath, 'utf8')
  if (!cmake.includes('generated/satsigner_payjoin.cpp')) {
    cmake = cmake.replace(
      '../cpp/react-native-payjoin.cpp\n    cpp-adapter.cpp',
      '../cpp/react-native-payjoin.cpp\n    ../cpp/generated/satsigner_payjoin.cpp\n    cpp-adapter.cpp'
    )
    fs.writeFileSync(cmakePath, cmake)
    console.log('patched android/CMakeLists.txt to link satsigner_payjoin.cpp')
  }
}

const indexPath = path.join(__dirname, '..', 'src', 'index.ts')
const contents = `import * as satsigner_payjoin from './generated/satsigner_payjoin'
// Generated by uniffi-bindgen-react-native — then patched for SatSigner facade.
import installer from './NativePayjoin'

let rustInstalled = false
let installError: unknown

if (!rustInstalled) {
  try {
    installer.installRustCrate()
    rustInstalled = true
  } catch (error) {
    installError = error
  }
}

let initialized = false
if (!initialized && rustInstalled) {
  try {
    satsigner_payjoin.default.initialize()
    initialized = true
  } catch (error) {
    // Stale APK / missing UniFFI symbols (e.g. http_post) after a JS-only
    // Metro reload. Keep the package importable so routes still load; the
    // facade reports isNativeAvailable() === false until a native rebuild.
    installError = error
    rustInstalled = false
    console.warn(
      '[react-native-payjoin] native init failed — rebuild the app to pick up PDK bindings',
      error
    )
  }
}

export async function uniffiInitAsync() {
  // NOOP for native; web would fetch WASM here.
}

// App-facing async facade (preferred import for SatSigner).
export {
  createReceiverSession,
  createSenderSession,
  fetchOhttpKeys,
  httpPost,
  isNativeAvailable,
  receiverContributeAndFinalize,
  receiverExtractRequest,
  receiverManualContribute,
  receiverManualFinalize,
  receiverProcessResponse,
  resumeReceiverSession,
  resumeSenderSession,
  senderExtractRequest,
  senderProcessResponse
} from './facade'

export type {
  HttpResponse,
  ProcessResult,
  ReceiverSessionHandle,
  ReceiverSessionInit,
  SenderSessionHandle,
  SenderSessionInit
} from './facade'

export function wasNativeInstallSuccessful(): boolean {
  return rustInstalled && installError === undefined
}

export default {
  satsigner_payjoin
}
`

fs.writeFileSync(indexPath, contents)
console.log('patched src/index.ts with SatSigner facade exports')
