// Generated by uniffi-bindgen-react-native — registerModule call required.
#include "react-native-payjoin.h"
#include "generated/satsigner_payjoin.hpp"

namespace payjoin {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeSatsignerPayjoin::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		NativeSatsignerPayjoin::unregisterModule(runtime);
		return false;
	}
}
