packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - '@shopify/react-native-skia'
  - esbuild
  - react-native-bdk-sdk
  - react-native-payjoin
  - sharp
  - '@secondts/bark-react-native'
  - workerd

overrides:
  react: 19.2.3
  react-dom: 19.2.3
  '@expo/metro-runtime': 57.0.6
  '@expo/dom-webview': 57.0.1
