packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - '@shopify/react-native-skia'
  - esbuild
  - react-native-bdk-sdk
  - react-native-payjoin
  - sharp
  - '@secondts/bark-react-native'
  - workerd

overrides:
  '@expo/dom-webview': 57.0.1
  '@expo/metro-runtime': 57.0.6
  react: 19.2.3
  react-dom: 19.2.3
patchedDependencies:
  react-native-draggable-flatlist@4.0.3: patches/react-native-draggable-flatlist@4.0.3.patch
  uniffi-bindgen-react-native@0.31.0-3: patches/uniffi-bindgen-react-native@0.31.0-3.patch
