// Generated by uniffi-bindgen-react-native — then patched for SatSigner facade.
import installer from './NativePayjoin'

let rustInstalled = false
let installError: unknown

if (!rustInstalled) {
  try {
    installer.installRustCrate()
    rustInstalled = true
  } catch (error) {
    installError = error
  }
}

import * as satsigner_payjoin from './generated/satsigner_payjoin'

let initialized = false
if (!initialized && rustInstalled) {
  satsigner_payjoin.default.initialize()
  initialized = true
}

export async function uniffiInitAsync() {
  // NOOP for native; web would fetch WASM here.
}

// App-facing async facade (preferred import for SatSigner).
export {
  createReceiverSession,
  createSenderSession,
  fetchOhttpKeys,
  isNativeAvailable,
  receiverContributeAndFinalize,
  receiverExtractRequest,
  receiverProcessResponse,
  resumeReceiverSession,
  resumeSenderSession,
  senderExtractRequest,
  senderProcessResponse
} from './facade'

export type {
  ProcessResult,
  ReceiverSessionHandle,
  ReceiverSessionInit,
  SenderSessionHandle,
  SenderSessionInit
} from './facade'

export function wasNativeInstallSuccessful(): boolean {
  return rustInstalled && installError === undefined
}

export default {
  satsigner_payjoin
}
