// Generated by uniffi-bindgen-react-native — then patched for SatSigner facade.
import installer from './NativePayjoin'

let rustInstalled = false
let installError: unknown

if (!rustInstalled) {
  try {
    installer.installRustCrate()
    rustInstalled = true
  } catch (error) {
    installError = error
  }
}

import * as satsigner_payjoin from './generated/satsigner_payjoin'

let initialized = false
if (!initialized && rustInstalled) {
  try {
    satsigner_payjoin.default.initialize()
    initialized = true
  } catch (error) {
    // Stale APK / missing UniFFI symbols (e.g. http_post) after a JS-only
    // Metro reload. Keep the package importable so routes still load; the
    // facade reports isNativeAvailable() === false until a native rebuild.
    installError = error
    rustInstalled = false
    console.warn(
      '[react-native-payjoin] native init failed — rebuild the app to pick up PDK bindings',
      error
    )
  }
}

export async function uniffiInitAsync() {
  // NOOP for native; web would fetch WASM here.
}

// App-facing async facade (preferred import for SatSigner).
export {
  createReceiverSession,
  createSenderSession,
  fetchOhttpKeys,
  httpPost,
  isNativeAvailable,
  receiverContributeAndFinalize,
  receiverExtractRequest,
  receiverProcessResponse,
  resumeReceiverSession,
  resumeSenderSession,
  senderExtractRequest,
  senderProcessResponse
} from './facade'

export type {
  HttpResponse,
  ProcessResult,
  ReceiverSessionHandle,
  ReceiverSessionInit,
  SenderSessionHandle,
  SenderSessionInit
} from './facade'

export function wasNativeInstallSuccessful(): boolean {
  return rustInstalled && installError === undefined
}

export default {
  satsigner_payjoin
}
