export const time = {
  seconds: (seconds: number) => seconds * 1000,
  secondsAfter: (date: number, seconds: number) => date + seconds * 1000,
  secondsBefore: (date: number, seconds: number) => date - seconds * 1000,
  minutes: (minutes: number) => time.seconds(minutes * 60),
  minutesAfter: (date: number, minutes: number) => date + time.seconds(minutes * 60),
  minutesBefore: (date: number, minutes: number) => date - time.seconds(minutes * 60),
  hours: (hours: number) => time.minutes(hours * 60),
  hoursAfter: (date: number, hours: number) => date + time.minutes(hours * 60),
  hoursBefore: (date: number, hours: number) => date - time.minutes(hours * 60),
  days: (days: number) => time.hours(days * 24),
  daysAfter: (date: number, days: number) => date + time.hours(days * 24),
  daysBefore: (date: number, days: number) => date - time.hours(days * 24),
  weeks: (weeks: number) => time.days(weeks * 7),
  weeksAfter: (date: number, weeks: number) => date + time.days(weeks * 7),
  weeksBefore: (date: number, weeks: number) => date - time.days(weeks * 7),
  now: () => (new Date()).getTime(),
  infinity: Infinity,
  zero: 0
}
