export const SATS_PER_BITCOIN = 100_000_000
export const MILLISATS_PER_SAT = 1000
export const DUST_LIMIT = 546
export const RECOMMENDED_BASE_FEE = 256
export const UNUSED_INTERNAL_ADDRESSES_NEEDED = 3
