import type { NostrRelay } from '@/types/models/Nostr'

export const NOSTR_RELAYS: NostrRelay[] = [
  // ── Curated defaults ─────────────────────────────────────────────────────────
  { name: 'Angani', url: 'wss://nostr-1.nbo.angani.co' },
  { name: 'Bitcoiner Social', url: 'wss://nostr.bitcoiner.social' },
  { name: 'Btc Library', url: 'wss://nostr.btc-library.com' },
  { name: 'Coracle', url: 'wss://bucket.coracle.social' },
  { name: 'Damus', url: 'wss://relay.damus.io' },
  { name: 'Data Haus', url: 'wss://nostr.data.haus' },
  { name: 'Dwadziesciajeden', url: 'wss://relay.dwadziesciajeden.pl' },
  { name: 'Einundzwanzig Space', url: 'wss://nostr.einundzwanzig.space' },
  { name: 'Mostro', url: 'wss://relay.mostro.network' },
  { name: 'Nos lol (POW 28 bits required)', url: 'wss://nos.lol' },
  { name: 'Nostr Band', url: 'wss://relay.nostr.band' },
  { name: 'Nostr BG', url: 'wss://relay.nostr.bg' },
  { name: 'Nostr Mom', url: 'wss://nostr.mom' },
  { name: 'Nostr Wine', url: 'wss://nostr.wine' },
  { name: 'Nostromo', url: 'wss://relay.nostromo.social' },
  { name: 'Nostrue', url: 'wss://nostrue.com' },
  { name: 'Offchain', url: 'wss://offchain.pub' },
  { name: 'Openhoofd', url: 'wss://strfry.openhoofd.nl' },
  { name: 'Primal', url: 'wss://relay.primal.net' },
  { name: 'Primal Premium', url: 'wss://premium.primal.net' },
  { name: 'Purple Relay', url: 'wss://ch.purplerelay.com' },
  { name: 'Sathoarder', url: 'wss://nostr.sathoarder.com' },
  { name: 'Satlantis', url: 'wss://relay.satlantis.io' },
  { name: 'Schneimi', url: 'wss://nostr.schneimi.de' },
  { name: 'Snort', url: 'wss://relay.snort.social' },
  { name: 'Swiss Enigma', url: 'wss://nostr.swiss-enigma.ch' },
  { name: 'Vulpem', url: 'wss://nostr.vulpem.com' },
  { name: 'YakiHonne', url: 'wss://nostr-01.yakihonne.com' },
  // ── Well-known public relays ──────────────────────────────────────────────────
  { name: '0xchat', url: 'wss://relay.0xchat.com' },
  { name: 'Agora', url: 'wss://relay.agora.social' },
  { name: 'Azzamo', url: 'wss://relay.azzamo.net' },
  { name: 'Bostr', url: 'wss://bostr.online' },
  { name: 'Creatr', url: 'wss://creatr.nostr.wine' },
  { name: 'Flashsoft', url: 'wss://relay.flashsoft.eu' },
  { name: 'Hodlbod', url: 'wss://relay.hodlbod.com' },
  { name: 'JB55', url: 'wss://relay.jb55.com' },
  { name: 'Lume', url: 'wss://relay.lume.nu' },
  { name: 'Mutinywallet', url: 'wss://nostr.mutinywallet.com' },
  { name: 'Nostr Land', url: 'wss://relay.nostr.land' },
  { name: 'Nostr Online', url: 'wss://relay.nostr.online' },
  { name: 'Nostr World', url: 'wss://relay.nostr.world' },
  { name: 'Nostrich House', url: 'wss://relay.nostrich.house' },
  { name: 'Orangepill', url: 'wss://relay.orangepill.dev' },
  { name: 'Plebs Town', url: 'wss://relay.plebs.town' },
  { name: 'Plebstr', url: 'wss://plebstr.com' },
  { name: 'Purplepag.es', url: 'wss://purplepag.es' },
  { name: 'Satoshi Stream', url: 'wss://relay.satoshi.stream' },
  { name: 'Siamstr', url: 'wss://siamstr.com' },
  { name: 'Stacker News', url: 'wss://relay.stacker.news' },
  { name: 'The Dude', url: 'wss://relay.thedude.cloud' },
  { name: 'Utxo One', url: 'wss://relay.utxo.one' },
  { name: 'Wellorder', url: 'wss://wellorder.net' },
  { name: 'Yakihonne', url: 'wss://relay.yakihonne.com' },
  { name: 'Zap Band', url: 'wss://relay.zap.band' },
  { name: 'Zapstore', url: 'wss://relay.zapstore.dev' }
]
