// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-payjoin.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNPayjoinSpec.h"

@interface Payjoin : NSObject <NativePayjoinSpec>
#else
#import <React/RCTBridgeModule.h>

@interface Payjoin : NSObject <RCTBridgeModule>
#endif

@end