name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
    types: [opened, synchronize, ready_for_review]

jobs:
  ci:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v3

      - name: set up node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: set up pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: get pnpm store directory
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: cache pnpm store
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: type check
        run: pnpm --filter @satsigner/mobile typecheck

      - name: lint & format
        run: pnpm run check

      - name: test
        run: pnpm --filter @satsigner/mobile test
