const PIN_KEY = 'satsigner_pin'

const PIN_SIZE = 4
const DEFAULT_PIN_MAX_TRIES = 5
const DEFAULT_LOCK_DELTA_TIME_SECONDS = 30
const SETTINGS_PIN_MIN_POSSIBLE_TRIES = 3
const SETTINGS_PIN_MAX_POSSIBLE_TRIES = 10

export {
  DEFAULT_LOCK_DELTA_TIME_SECONDS,
  DEFAULT_PIN_MAX_TRIES,
  PIN_KEY,
  PIN_SIZE,
  SETTINGS_PIN_MAX_POSSIBLE_TRIES,
  SETTINGS_PIN_MIN_POSSIBLE_TRIES
}
