const PIN_KEY = 'satsigner_pin'
const DURESS_PIN_KEY = 'satsigner_duress_pin'
const DEFAULT_PIN_KEY = 'satsigner_default_pin'
const SALT_KEY = 'satsigner_salt'
const SALT_KEY_DURESS = 'satsigner_salt_duress'

const DEFAULT_PIN = '2121'
const PIN_SIZE = 4
const DEFAULT_PIN_MAX_TRIES = 5
const DEFAULT_LOCK_DELTA_TIME_SECONDS = 30
const SETTINGS_PIN_MIN_POSSIBLE_TRIES = 3
const SETTINGS_PIN_MAX_POSSIBLE_TRIES = 10

export {
  DEFAULT_LOCK_DELTA_TIME_SECONDS,
  DEFAULT_PIN,
  DEFAULT_PIN_MAX_TRIES,
  DEFAULT_PIN_KEY,
  DURESS_PIN_KEY,
  PIN_KEY,
  PIN_SIZE,
  SALT_KEY,
  SALT_KEY_DURESS,
  SETTINGS_PIN_MAX_POSSIBLE_TRIES,
  SETTINGS_PIN_MIN_POSSIBLE_TRIES
}
