const DEFAULT_MULTISIG_KEY_COUNT = 3
const DEFAULT_MULTISIG_KEYS_REQUIRED = 2
const MAX_MULTISIG_KEYS = 15

export {
  DEFAULT_MULTISIG_KEY_COUNT,
  DEFAULT_MULTISIG_KEYS_REQUIRED,
  MAX_MULTISIG_KEYS
}
